// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPeeo0Trm8OgvSx7u9tdX8Vmj4hW_GoYc',
    appId: '1:240434334217:web:b132f57b27922416c086d8',
    messagingSenderId: '240434334217',
    projectId: 'alleventspro-aa866',
    authDomain: 'alleventspro-aa866.firebaseapp.com',
    storageBucket: 'alleventspro-aa866.firebasestorage.app',
    measurementId: 'G-H6D73SB6E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlccTw5qG1c56zx5tzv-wbGK3TDsHTzoM',
    appId: '1:240434334217:android:2df6ac7c51769470c086d8',
    messagingSenderId: '240434334217',
    projectId: 'alleventspro-aa866',
    storageBucket: 'alleventspro-aa866.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgMtYto6L6yyPXGxqIQbKzgKl3pnMewWQ',
    appId: '1:240434334217:ios:e5acacb636fa183cc086d8',
    messagingSenderId: '240434334217',
    projectId: 'alleventspro-aa866',
    storageBucket: 'alleventspro-aa866.firebasestorage.app',
    iosBundleId: 'com.example.alleventsPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPeeo0Trm8OgvSx7u9tdX8Vmj4hW_GoYc',
    appId: '1:240434334217:web:6cb2459447e7c341c086d8',
    messagingSenderId: '240434334217',
    projectId: 'alleventspro-aa866',
    authDomain: 'alleventspro-aa866.firebaseapp.com',
    storageBucket: 'alleventspro-aa866.firebasestorage.app',
    measurementId: 'G-PL0QFYHMLL',
  );
}
